backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/products/index.md"
        label: "Sample Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/about/index.md"
        label: "About Primoko"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: "Join Team", name: joinTeam, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: button, name: button, widget: text}, {label: Description, name: description, widget: text}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "First Section", name: firstSection, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}, {label: "Link Text", name: linkText, widget: text}]}
          - {label: "Second Section", name: secondSection, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "src/pages/services/index.md"
        label: "Services Overview Page"
        name: "overview"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services/index"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Seprator Image", name: sepratorImage, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Humanoko, name: humanoko, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Button, name: button, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}, {label: Role, name: authorRole, widget: string}]}
          - {label: Technologies, name: technologies, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Tags, name: tags, widget: string}, {label: "Helper Text", name: helperText, widget: string}, {label: "Button Text", name: buttonText, widget: string}]}
      - file: "src/pages/services/mobile.md"
        label: "Services Mobile Page"
        name: "mobile"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services/mobile"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: "Right List", name: rightList, widget: string}
          - {label: "Left List", name: leftList, widget: string}
          - {label: Others, name: others, widget: text}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}, {label: Role, name: authorRole, widget: string}]}
      - file: "src/pages/services/web.md"
        label: "Services Web Page"
        name: "web"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services/web"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: "Right List", name: rightList, widget: string}
          - {label: "Left List", name: leftList, widget: string}
          - {label: Others, name: others, widget: text}
      - file: "src/pages/services/devops.md"
        label: "Services DevOps Page"
        name: "devops"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services/devops"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: text}
      - file: "src/pages/services/salesforce.md"
        label: "Services Salesforce Page"
        name: "salesforce"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services/salesforce"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}, {label: Role, name: authorRole, widget: string}]}
      - file: "src/pages/services/pricing.md"
        label: "Services Pricing Page"
        name: "pricing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services/pricing"}
          - {label: Title, name: title, widget: string}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}, {label: Note, name: note, widget: string}, {label: Project, name: project, widget: string}, {label: Examples, name: examples, widget: list}, {label: Image, name: image, widget: image}]}]}
      